name: Build Citron

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y vib docker.io

      - name: Build rootfs tarball
        run: vib build recipe.yml --tar --id citron

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v5
        with:
          name: citron-rootfs
          path: ./custom-rootfs.tar

      - name: Publish to GHCR
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$CR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag citron:latest ghcr.io/${{ github.repository_owner }}/citron:latest
          docker push ghcr.io/${{ github.repository_owner }}/citron:latest
